export interface Video {
  id: string;
  title: string;
}

export interface VideoCategory {
  name: string;
  videos: Video[];
}

/* The nine galleries on simplebooks.com/srilanka/videos/.
   A few videos are listed under two categories on the live site; kept as published. */
export const videoCategories: VideoCategory[] = [
  {
    name: "Business Interviews",
    videos: [
      { id: "trW1LW4Nhn0", title: "How to raise funds for a startup | Imthiyaaz Hassim - Sixer Video (Sinhala)" },
      { id: "h7km_zfRqoM", title: "What you should consider before starting a business | Bhanuka Harischandra - Surge Global" },
      { id: "uDoZN7wQwkM", title: "Dropshipping - How to start dropshipping | Nawran Nabawi (Sinhala)" },
      { id: "PC-1Qc2OHfI", title: "Digital marketing | How to start digital marketing for your business - Bhanuka Harischandra" },
      { id: "wRI2B5ldAiA", title: "Online business sinhala | How to start an online business - Nawran Nabawi" },
      { id: "FrXsBV2sx1g", title: "Best business ideas from a global award winning entrepreneur | Business tips" },
      { id: "C7jXgsbtrAM", title: "How to use technology for your business | Start a business" },
      { id: "VfZ6rEzWj6I", title: "Fiverr Sinhala | How to make money on Fiverr - tecHCD" },
      { id: "PNj0_Soy5gw", title: "Online jobs Sinhala | How to make money online - tecHCD" },
      { id: "pirCFqvDJQc", title: "How To Create a YouTube Channel in Sinhala 2021 |Janeeth Rodrigo - Ideahell Founder" },
      { id: "hkvCNtuMbAw", title: "How To Start Content Marketing For Your Business? - Janeeth Rodrigo| Ideahell (Sinhala)" },
      { id: "XvcTth5tbPY", title: "Amithe Gamage LinkedIn Sinhala | How To Use LinkedIn For Your Business?" },
      { id: "GvrcB2hQ708", title: "Marketing Strategies To Start a Successful Business | Inthikab Zufer Sinhala" },
      { id: "vEecPz0ybNo", title: "Pricing Strategies | How To Price Your Product or Service? - Aloka Gunasekara Sinhala" },
      { id: "H1VPAwFclgY", title: "E Commerce Sinhala | How To Start an E commerce Business - Madushanka Wijewickrama" },
      { id: "ljRFhwl1iLM", title: "The Art of Selling Sinhala | Strategies To Sell Your Product or Service -Dilrukshan Fernando Sales" },
    ],
  },
  {
    name: "Business Registration",
    videos: [
      { id: "IbJFWtvYo-A", title: "How To Register A Business In Sri Lanka | Simplebooks" },
      { id: "RWVgsUf2aCI", title: "Simplebooks Invoicing Tool For Small Businesses In Sri Lanka" },
      { id: "k9xW4R9g2kE", title: "Register Your Business Quickly And Easily Through Simplebooks Dashboard" },
      { id: "fNbgHuw8VgY", title: "How to start a business with a foreign partner in Sri Lanka - Simplebooks (Sinhala)" },
      { id: "JjNcudWOj8Y", title: "Do you need a physical address for your business? (Crash course on business addresses!) -Simplebooks" },
      { id: "y76YkWJxggQ", title: "10 benefits of registering your private limited company - Simplebooks Sri Lanka" },
      { id: "Ibr8qdhIF44", title: "The guide for the online registration with Sri Lanka customs - Simplebooks" },
      { id: "_ZTnxwqkWcg", title: "How to get a bank loan for your business | Tips for startups - Simplebooks (Sinhala)" },
      { id: "38ZayuBZvaM", title: "What should you do after company registration? (6 important steps ) - Simplebooks - Sinhala" },
      { id: "1gLXJ9A1_NI", title: "Company Secretary - (Why do you need a company secretary for your company?) - Simplebooks" },
      { id: "WKNKvRh6wIM", title: "Nonprofit organization එකක් start කරලා ඒක register කරනකන් කරන්න ඕන හැමදෙයක්ම දැනගන්න- Simplebooks" },
      { id: "KIdQCTiDFDo", title: "How to register a private limited company in Sri Lanka? (company එක online ගිහින් register කරමු)" },
      { id: "99GeckIuklc", title: "What is company articles of association? | Company එක register කරන්න කලින් මේක දැනගන්න - Simplebooks" },
      { id: "HcO79tLS68U", title: "Business registration -Sri Lanka | How to choose the right business registration type?" },
      { id: "-iYKYN2oyE0", title: "sole proprietorship registration | තනි පුද්ගල ව්‍යාපාර ලියාපදිංචිය සරල පියවර වලින් - Simplebooks" },
      { id: "j5LSEaPpwEQ", title: "Company Registration පිළිබඳ හැමෝම අහන ප්‍රශ්න | FAQ - Simplebooks (Sinhala)" },
    ],
  },
  {
    name: "Start a Business",
    videos: [
      { id: "a4pDNa_3De8", title: "How to start your own business | 6 main steps to launching a successful startup|Simplebooks" },
      { id: "eicHkBee5Lw", title: "How to start your export business in Sri Lanka - (Step by step process) Simplebooks" },
      { id: "infiAbyFrDU", title: "How to start your import business in Sri Lanka | Step by step process - Simplebooks" },
      { id: "fH5OVAmpXdo", title: "Business ideas - How to find your own business idea - Simplebooks (Sinhala)" },
      { id: "TiP4IpOORUU", title: "11 ways to find funding for startups | Funding a business" },
      { id: "agjQsCN37GI", title: "Freelancing Business Ideas - Simplebooks Sinhala" },
      { id: "yrs-VmFyR14", title: "How To Write a Business Plan | Business Plan Sinhala - Simplebooks" },
      { id: "bNe5zzt7YfY", title: "How To Bootstrap Your Startup | 8 Bootstrapping Strategies To Start Your Business - Simplebooks" },
      { id: "zn-BsEW5DFo", title: "Elon Musk Case Study | How Did Elon Musk Overcome Failures To become Super Rich - Simplebooks" },
      { id: "kjPJnK4PbCY", title: "Strategies To Make Your Customers To Buy More From Your Business | Simplebooks" },
      { id: "zPqpYz0QtF0", title: "IPL Championships Prize Money| Indian Premier League 2021- Simplebooks" },
      { id: "dPwaTOwistA", title: "Strategies To Control The Inventory In Your Business | How To Manage Your Inventory - Simplebooks" },
      { id: "YWusPS-QtQI", title: "6 Ultimate Benefits You Get Only From Starting an E Commerce Business - Simplebooks" },
      { id: "IEx1vyNvJp8", title: "How To Raise Funds For Your Startup | Startup Funding - Chalinda Abeykoon - Simplebooks" },
      { id: "-msyoQJkfA4", title: "How to Write a Detailed Business Plan | Business Consultant Chaaminda Kumarasiri" },
      { id: "BErnEj1eKVw", title: "Budget 2022 Sri Lanka | Simplebooks - Sinhala" },
    ],
  },
  {
    name: "Finance/Bookkeeping for Startup Owners",
    videos: [
      { id: "UKq5ihYmNm4", title: "7 important source documents a business owner should keep for bookkeeping and tax - Sinhala" },
      { id: "WCC8qAfNItU", title: "9 tips to maintain your source documents online | Bookkeeping - Sinhala" },
      { id: "modqqrSifeo", title: "4 ways to pay yourself from your limited company | Simplebooks" },
      { id: "2Jns9L6-tNo", title: "Startup owner's guide to bookkeeping - Simplebooks(Sinhala)" },
      { id: "6R0wc3ONsFE", title: "Best online accounting software's for your business | Simplebooks (Sinhala)" },
      { id: "pTRfqDA3Wao", title: "How to read financial statements for a company (with zero finance knowledge)" },
      { id: "pAhi-PykbiU", title: "Annual return vs Tax return | Difference between annual return and tax return in your company?" },
      { id: "r0Y-niJvqTQ", title: "How to increase your profits by understanding profit and loss statement?" },
      { id: "ebNgE9HdbXw", title: "How to read and understand your balance sheet? - Bookkeeping Sinhala" },
      { id: "UGgWT-goxos", title: "How to read a cash flow statement | Cash flow statement for business owners" },
      { id: "ZwaJw1q-k8A", title: "Working Capital Management | How To Improve Your Working Capital?" },
      { id: "DgdiAAjyNG8", title: "9 Ways To Save Money In Your Business | How To Save Money? - Simplebooks Sinhala" },
      { id: "bNe5zzt7YfY", title: "How To Bootstrap Your Startup | 8 Bootstrapping Strategies To Start Your Business - Simplebooks" },
      { id: "kjPJnK4PbCY", title: "Strategies To Make Your Customers To Buy More From Your Business | Simplebooks" },
      { id: "dPwaTOwistA", title: "Strategies To Control The Inventory In Your Business | How To Manage Your Inventory - Simplebooks" },
      { id: "XjQ9yqoFn1E", title: "QuickBooks Sri Lanka | How To Use QuickBooks For Your Businesses Bookkeeping - Simplebooks" },
    ],
  },
  {
    name: "Labor Law & Payroll Management",
    videos: [
      { id: "lWsuogRAPx8", title: "What should you do after hiring employees? | Tips on how to retain staff! - (Payroll management)" },
      { id: "4n-tN-UeDbM", title: "8 labour laws you need to know if you have employees| Simplebooks" },
      { id: "QKat4GsFsGs", title: "EPF/ETF in Sri Lanka | ඔයාගේ employees ලට EPF/ETF ගෙවන්නේ කොහොමද? - Simplebooks (Sinhala)" },
      { id: "XjQ9yqoFn1E", title: "QuickBooks Sri Lanka | How To Use QuickBooks For Your Businesses Bookkeeping - Simplebooks" },
      { id: "nCMYFjGbjtY", title: "How To Grow a Small Business Into a Large Business? | Shopbook App" },
      { id: "-TqGglTK9MU", title: "How To Use Shopbook To Grow Your Small Business - Simplebooks" },
      { id: "AZ7V2oRxDKI", title: "How To Manage Payroll For Small Businesses In Sri Lanka | Simplebooks" },
      { id: "4pNVMlIDP2g", title: "What Should You Do After Hiring Employees? | 2024 Payroll Management Update | Simplebooks" },
      { id: "LakIbbI7VMk", title: "EPF/ETF 2024 Updates in Sinhala | What is the Difference between ETF and EPF? | Simplebooks" },
      { id: "nHlVYPDDInA", title: "Mastering Payroll Management : Your Ultimate Guide | Free Webinar" },
    ],
  },
  {
    name: "Company Law in Sri Lanka",
    videos: [
      { id: "lkrOV8182Zo", title: "How To Appoint and Remove a Company Director (Sinhala) - Simplebooks Sri Lanka" },
      { id: "GykmfPaYDiE", title: "How To Appoint a Shareholder | How can a Shareholder Exit The Company- Simplebooks (Sinhala)" },
      { id: "cCmImWx4YNQ", title: "How to closedown a company | Company එක වහන්න කලින් දැනගත යුතු දේවල්-Simplebooks" },
      { id: "JjNcudWOj8Y", title: "Do you need a physical address for your business? (Crash course on business addresses!) -Simplebooks" },
      { id: "zadi17MHBmQ", title: "What is an annual return (a step by step guide on how to file an annual return) - Simplebooks" },
    ],
  },
  {
    name: "Tax in Sri Lanka",
    videos: [
      { id: "NJ5Darcnga8", title: "Statement of Estimated Income Tax Payable - Tax Computation -Simplebooks.com (Sinhala)" },
      { id: "6xSD2saaAaY", title: "What type of tax does your company need to pay? -These taxes could affect your company - Simplebooks" },
      { id: "9elTeuCNKMA", title: "What is a Tax Return- ඇයි November 30 එතරම් වැදගත්- Simplebooks (Sinhala)" },
      { id: "RS_6Bzm9U4I", title: "Corporate Tax ගැන සියල්ල (step by step guide) - Simplebooks Sri Lanka" },
      { id: "GllI44uCbRc", title: "Individual Income Tax එක calculate කරන්නෙ මෙහෙමයි - Simplebooks Sri Lanka (Sinhala)" },
      { id: "X2Qrmi450nM", title: "VAT registration | The guide on how to register your business for VAT in Sri Lanka - Simplebooks" },
      { id: "6dR_7MTXNys", title: "How to Calculate APIT Tax and PAYE Tax? මාසේ පඩියෙන් කීයක් tax කැපෙනවද?(Sinhala)" },
      { id: "6g_AkRI0nC4", title: "11 secret ways to reduce your tax legally - Simplebooks (Sinhala)" },
      { id: "VRf0zrDWBKk", title: "Everything a company owner should know about auditing - Simplebooks (Sinhala)" },
      { id: "tfleKFuoEIM", title: "Tax in Sri Lanka | 7 secrets to reduce your companies tax - Simplebooks" },
      { id: "BErnEj1eKVw", title: "Budget 2022 Sri Lanka | Simplebooks - Sinhala" },
      { id: "OPxMdkifY0c", title: "Social Security Contribution Levy Tax | Simplebooks" },
      { id: "pcL87NiLIrg", title: "New Tax Changes In Sri Lanka | Everyone Should know this! | Simplebooks" },
      { id: "dndzAzeFoyg", title: "Foreign Income Tax In Sri Lanka | Simplebooks Tax" },
      { id: "_6uvCB7Nl64", title: "Who should open the tax files 01.06.2023| New tax changes in Sri Lanka | Simplebooks" },
      { id: "oqJ1HPDvUAw", title: "How to Calculate Your Tax Easily and Quickly? | Income Tax Calculator | Simplebooks" },
    ],
  },
  {
    name: "Business Agreements",
    videos: [
      { id: "SakR-rHZUss", title: "12 Things To Have in Your Employment Agreement | Jobs in Sri Lanka" },
      { id: "88-FBjHEFM4", title: "How To Protect Confidential Information In Your Business | Non Disclosure Agreement - NDA" },
      { id: "sMvIqGiGD-A", title: "How To Prepare a Shareholder Agreement With Your Business Partner? - Simplebooks" },
      { id: "dZqOSwlrZ5U", title: "How To Make Your Business Negotiations Legally binding | Mutual Agreement - Simplebooks" },
    ],
  },
  {
    name: "Case Studies",
    videos: [
      { id: "1wh7sPIvcCQ", title: "Steve Jobs Case Study - The Revolution Of Apple Company - Simplebooks" },
      { id: "f4XrRScRuZE", title: "How to start a successful business during coronavirus | 15 coronavirus - proof business ideas" },
      { id: "Nyx_Lbiucu4", title: "Colombo Port City | How To Start a Business In Port City Sri Lanka" },
      { id: "WT3G_ShDgVE", title: "IPL 2021 | How Indian Premier League Makes Money | Cricket" },
      { id: "nYb4BFWBOgI", title: "The Business World In 2050 | How Will The Future World Be Like? -Simplebooks Sinhala" },
      { id: "zn-BsEW5DFo", title: "Elon Musk Case Study | How Did Elon Musk Overcome Failures To become Super Rich - Simplebooks" },
      { id: "FFs1sd2oeHY", title: "Sundar Pichai Case Study | How Sundar Pichai Rose To Become CEO Of Google - Simplebooks" },
      { id: "LMION8sOs40", title: "Bill Gates Case Study | Story Of Becoming The Worlds Richest Billionaire After Starting Microsoft" },
      { id: "HABYr0pVQS4", title: "Warren Buffet Case Study | How Did Warren Buffet Become Super Rich as The Most Successful Investor" },
      { id: "znL4FmIANBE", title: "Jeff Bezos Case Study | Business Lessons On How Amazon Became The Worlds Internet Giant" },
      { id: "cbudNi_xE1I", title: "Singapore Case Study | How Did Lee Kuan Yew Made Singapore Super Rich" },
      { id: "7g6CmD2UJ_s", title: "Why Nokia Failed? | Business Case Study On Nokia | Simplebooks" },
      { id: "StPADrELnwU", title: "Why Kodak Failed? | Business Case Study On Kodak | Simplebooks" },
      { id: "zOb78vcGdD4", title: "Thank You For Supporting Simplebooks To Reach 100,000 YouTube Subscribers!" },
      { id: "7URv5d4ClTo", title: "Tik Tok Case Study | How Tik Tok Became The Number One Social Media App | Simplebooks" },
      { id: "6iB1eKfOPK0", title: "What Is Metaverse And How It Will Change Millions Of People | Simplebooks Case Study" },
    ],
  },
];
